name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 8.15.9

      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 20

      - run: pnpm install --frozen-lockfile
      - run: pnpm test
      - run: pnpm build

  compatibility:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 8.15.9

      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 20

      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm test:matrix
